### ISSUE TITLE
Dgeni is not defined

### ISSUE THREAD

**Issue by darkmavis1980** [petebacondarwin/dgeni-example#14]
For some reasons when I launch the grunt task it says that Dgeni is not defined, even if Dgeni is installed (globally and locally), anybody else had the same issue?

**Comment by c0bra** [comment]
@petebacondarwin I think you can close this due to 696c4c6, right? Arrays seem to be working great for me.

**Comment by petebacondarwin** [comment]
I would say so. Thanks @c0bra
